/* automatically generated by rust-bindgen 0.71.1 */

pub const _STDINT_H: u32 = 1;
pub const _FEATURES_H: u32 = 1;
pub const _DEFAULT_SOURCE: u32 = 1;
pub const __GLIBC_USE_ISOC2Y: u32 = 0;
pub const __GLIBC_USE_ISOC23: u32 = 0;
pub const __USE_ISOC11: u32 = 1;
pub const __USE_ISOC99: u32 = 1;
pub const __USE_ISOC95: u32 = 1;
pub const __USE_POSIX_IMPLICITLY: u32 = 1;
pub const _POSIX_SOURCE: u32 = 1;
pub const _POSIX_C_SOURCE: u32 = 200809;
pub const __USE_POSIX: u32 = 1;
pub const __USE_POSIX2: u32 = 1;
pub const __USE_POSIX199309: u32 = 1;
pub const __USE_POSIX199506: u32 = 1;
pub const __USE_XOPEN2K: u32 = 1;
pub const __USE_XOPEN2K8: u32 = 1;
pub const _ATFILE_SOURCE: u32 = 1;
pub const __WORDSIZE: u32 = 64;
pub const __WORDSIZE_TIME64_COMPAT32: u32 = 1;
pub const __SYSCALL_WORDSIZE: u32 = 64;
pub const __TIMESIZE: u32 = 64;
pub const __USE_TIME_BITS64: u32 = 1;
pub const __USE_MISC: u32 = 1;
pub const __USE_ATFILE: u32 = 1;
pub const __USE_FORTIFY_LEVEL: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_GETS: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_SCANF: u32 = 0;
pub const __GLIBC_USE_C23_STRTOL: u32 = 0;
pub const _STDC_PREDEF_H: u32 = 1;
pub const __STDC_IEC_559__: u32 = 1;
pub const __STDC_IEC_60559_BFP__: u32 = 201404;
pub const __STDC_IEC_559_COMPLEX__: u32 = 1;
pub const __STDC_IEC_60559_COMPLEX__: u32 = 201404;
pub const __STDC_ISO_10646__: u32 = 201706;
pub const __GNU_LIBRARY__: u32 = 6;
pub const __GLIBC__: u32 = 2;
pub const __GLIBC_MINOR__: u32 = 42;
pub const _SYS_CDEFS_H: u32 = 1;
pub const __glibc_c99_flexarr_available: u32 = 1;
pub const __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI: u32 = 0;
pub const __HAVE_GENERIC_SELECTION: u32 = 1;
pub const __GLIBC_USE_LIB_EXT2: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT_C23: u32 = 0;
pub const __GLIBC_USE_IEC_60559_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT_C23: u32 = 0;
pub const __GLIBC_USE_IEC_60559_TYPES_EXT: u32 = 0;
pub const _BITS_TYPES_H: u32 = 1;
pub const _BITS_TYPESIZES_H: u32 = 1;
pub const __OFF_T_MATCHES_OFF64_T: u32 = 1;
pub const __INO_T_MATCHES_INO64_T: u32 = 1;
pub const __RLIM_T_MATCHES_RLIM64_T: u32 = 1;
pub const __STATFS_MATCHES_STATFS64: u32 = 1;
pub const __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64: u32 = 1;
pub const __FD_SETSIZE: u32 = 1024;
pub const _BITS_TIME64_H: u32 = 1;
pub const _BITS_WCHAR_H: u32 = 1;
pub const _BITS_STDINT_INTN_H: u32 = 1;
pub const _BITS_STDINT_UINTN_H: u32 = 1;
pub const _BITS_STDINT_LEAST_H: u32 = 1;
pub const INT8_MIN: i32 = -128;
pub const INT16_MIN: i32 = -32768;
pub const INT32_MIN: i32 = -2147483648;
pub const INT8_MAX: u32 = 127;
pub const INT16_MAX: u32 = 32767;
pub const INT32_MAX: u32 = 2147483647;
pub const UINT8_MAX: u32 = 255;
pub const UINT16_MAX: u32 = 65535;
pub const UINT32_MAX: u32 = 4294967295;
pub const INT_LEAST8_MIN: i32 = -128;
pub const INT_LEAST16_MIN: i32 = -32768;
pub const INT_LEAST32_MIN: i32 = -2147483648;
pub const INT_LEAST8_MAX: u32 = 127;
pub const INT_LEAST16_MAX: u32 = 32767;
pub const INT_LEAST32_MAX: u32 = 2147483647;
pub const UINT_LEAST8_MAX: u32 = 255;
pub const UINT_LEAST16_MAX: u32 = 65535;
pub const UINT_LEAST32_MAX: u32 = 4294967295;
pub const INT_FAST8_MIN: i32 = -128;
pub const INT_FAST16_MIN: i64 = -9223372036854775808;
pub const INT_FAST32_MIN: i64 = -9223372036854775808;
pub const INT_FAST8_MAX: u32 = 127;
pub const INT_FAST16_MAX: u64 = 9223372036854775807;
pub const INT_FAST32_MAX: u64 = 9223372036854775807;
pub const UINT_FAST8_MAX: u32 = 255;
pub const UINT_FAST16_MAX: i32 = -1;
pub const UINT_FAST32_MAX: i32 = -1;
pub const INTPTR_MIN: i64 = -9223372036854775808;
pub const INTPTR_MAX: u64 = 9223372036854775807;
pub const UINTPTR_MAX: i32 = -1;
pub const PTRDIFF_MIN: i64 = -9223372036854775808;
pub const PTRDIFF_MAX: u64 = 9223372036854775807;
pub const SIG_ATOMIC_MIN: i32 = -2147483648;
pub const SIG_ATOMIC_MAX: u32 = 2147483647;
pub const SIZE_MAX: i32 = -1;
pub const WINT_MIN: u32 = 0;
pub const WINT_MAX: u32 = 4294967295;
pub const __bool_true_false_are_defined: u32 = 1;
pub const true_: u32 = 1;
pub const false_: u32 = 0;
pub type wchar_t = ::std::os::raw::c_int;
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct max_align_t {
    pub __clang_max_align_nonce1: ::std::os::raw::c_longlong,
    pub __bindgen_padding_0: u64,
    pub __clang_max_align_nonce2: u128,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of max_align_t"][::std::mem::size_of::<max_align_t>() - 32usize];
    ["Alignment of max_align_t"][::std::mem::align_of::<max_align_t>() - 16usize];
    ["Offset of field: max_align_t::__clang_max_align_nonce1"]
        [::std::mem::offset_of!(max_align_t, __clang_max_align_nonce1) - 0usize];
    ["Offset of field: max_align_t::__clang_max_align_nonce2"]
        [::std::mem::offset_of!(max_align_t, __clang_max_align_nonce2) - 16usize];
};
pub type __u_char = ::std::os::raw::c_uchar;
pub type __u_short = ::std::os::raw::c_ushort;
pub type __u_int = ::std::os::raw::c_uint;
pub type __u_long = ::std::os::raw::c_ulong;
pub type __int8_t = ::std::os::raw::c_schar;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int16_t = ::std::os::raw::c_short;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __int64_t = ::std::os::raw::c_long;
pub type __uint64_t = ::std::os::raw::c_ulong;
pub type __int_least8_t = __int8_t;
pub type __uint_least8_t = __uint8_t;
pub type __int_least16_t = __int16_t;
pub type __uint_least16_t = __uint16_t;
pub type __int_least32_t = __int32_t;
pub type __uint_least32_t = __uint32_t;
pub type __int_least64_t = __int64_t;
pub type __uint_least64_t = __uint64_t;
pub type __quad_t = ::std::os::raw::c_long;
pub type __u_quad_t = ::std::os::raw::c_ulong;
pub type __intmax_t = ::std::os::raw::c_long;
pub type __uintmax_t = ::std::os::raw::c_ulong;
pub type __dev_t = ::std::os::raw::c_ulong;
pub type __uid_t = ::std::os::raw::c_uint;
pub type __gid_t = ::std::os::raw::c_uint;
pub type __ino_t = ::std::os::raw::c_ulong;
pub type __ino64_t = ::std::os::raw::c_ulong;
pub type __mode_t = ::std::os::raw::c_uint;
pub type __nlink_t = ::std::os::raw::c_ulong;
pub type __off_t = ::std::os::raw::c_long;
pub type __off64_t = ::std::os::raw::c_long;
pub type __pid_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __fsid_t {
    pub __val: [::std::os::raw::c_int; 2usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __fsid_t"][::std::mem::size_of::<__fsid_t>() - 8usize];
    ["Alignment of __fsid_t"][::std::mem::align_of::<__fsid_t>() - 4usize];
    ["Offset of field: __fsid_t::__val"][::std::mem::offset_of!(__fsid_t, __val) - 0usize];
};
pub type __clock_t = ::std::os::raw::c_long;
pub type __rlim_t = ::std::os::raw::c_ulong;
pub type __rlim64_t = ::std::os::raw::c_ulong;
pub type __id_t = ::std::os::raw::c_uint;
pub type __time_t = ::std::os::raw::c_long;
pub type __useconds_t = ::std::os::raw::c_uint;
pub type __suseconds_t = ::std::os::raw::c_long;
pub type __suseconds64_t = ::std::os::raw::c_long;
pub type __daddr_t = ::std::os::raw::c_int;
pub type __key_t = ::std::os::raw::c_int;
pub type __clockid_t = ::std::os::raw::c_int;
pub type __timer_t = *mut ::std::os::raw::c_void;
pub type __blksize_t = ::std::os::raw::c_long;
pub type __blkcnt_t = ::std::os::raw::c_long;
pub type __blkcnt64_t = ::std::os::raw::c_long;
pub type __fsblkcnt_t = ::std::os::raw::c_ulong;
pub type __fsblkcnt64_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt64_t = ::std::os::raw::c_ulong;
pub type __fsword_t = ::std::os::raw::c_long;
pub type __ssize_t = ::std::os::raw::c_long;
pub type __syscall_slong_t = ::std::os::raw::c_long;
pub type __syscall_ulong_t = ::std::os::raw::c_ulong;
pub type __loff_t = __off64_t;
pub type __caddr_t = *mut ::std::os::raw::c_char;
pub type __intptr_t = ::std::os::raw::c_long;
pub type __socklen_t = ::std::os::raw::c_uint;
pub type __sig_atomic_t = ::std::os::raw::c_int;
pub type int_least8_t = __int_least8_t;
pub type int_least16_t = __int_least16_t;
pub type int_least32_t = __int_least32_t;
pub type int_least64_t = __int_least64_t;
pub type uint_least8_t = __uint_least8_t;
pub type uint_least16_t = __uint_least16_t;
pub type uint_least32_t = __uint_least32_t;
pub type uint_least64_t = __uint_least64_t;
pub type int_fast8_t = ::std::os::raw::c_schar;
pub type int_fast16_t = ::std::os::raw::c_long;
pub type int_fast32_t = ::std::os::raw::c_long;
pub type int_fast64_t = ::std::os::raw::c_long;
pub type uint_fast8_t = ::std::os::raw::c_uchar;
pub type uint_fast16_t = ::std::os::raw::c_ulong;
pub type uint_fast32_t = ::std::os::raw::c_ulong;
pub type uint_fast64_t = ::std::os::raw::c_ulong;
pub type intmax_t = __intmax_t;
pub type uintmax_t = __uintmax_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sourcepp_buffer_t {
    pub size: i64,
    pub data: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of sourcepp_buffer_t"][::std::mem::size_of::<sourcepp_buffer_t>() - 16usize];
    ["Alignment of sourcepp_buffer_t"][::std::mem::align_of::<sourcepp_buffer_t>() - 8usize];
    ["Offset of field: sourcepp_buffer_t::size"]
        [::std::mem::offset_of!(sourcepp_buffer_t, size) - 0usize];
    ["Offset of field: sourcepp_buffer_t::data"]
        [::std::mem::offset_of!(sourcepp_buffer_t, data) - 8usize];
};
unsafe extern "C" {
    pub fn sourcepp_buffer_new(size: usize) -> sourcepp_buffer_t;
}
unsafe extern "C" {
    pub fn sourcepp_buffer_free(buffer: *mut sourcepp_buffer_t);
}
pub type sourcepp_buffer_uint32_t = sourcepp_buffer_t;
pub type sourcepp_buffer_uint64_t = sourcepp_buffer_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sourcepp_string_t {
    pub size: i64,
    pub data: *mut u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of sourcepp_string_t"][::std::mem::size_of::<sourcepp_string_t>() - 16usize];
    ["Alignment of sourcepp_string_t"][::std::mem::align_of::<sourcepp_string_t>() - 8usize];
    ["Offset of field: sourcepp_string_t::size"]
        [::std::mem::offset_of!(sourcepp_string_t, size) - 0usize];
    ["Offset of field: sourcepp_string_t::data"]
        [::std::mem::offset_of!(sourcepp_string_t, data) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sourcepp_string_array_t {
    pub size: i64,
    pub data: *mut *mut ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of sourcepp_string_array_t"][::std::mem::size_of::<sourcepp_string_array_t>() - 16usize];
    ["Alignment of sourcepp_string_array_t"]
        [::std::mem::align_of::<sourcepp_string_array_t>() - 8usize];
    ["Offset of field: sourcepp_string_array_t::size"]
        [::std::mem::offset_of!(sourcepp_string_array_t, size) - 0usize];
    ["Offset of field: sourcepp_string_array_t::data"]
        [::std::mem::offset_of!(sourcepp_string_array_t, data) - 8usize];
};
unsafe extern "C" {
    pub fn sourcepp_string_new(size: usize) -> sourcepp_string_t;
}
unsafe extern "C" {
    pub fn sourcepp_string_free(str_: *mut sourcepp_string_t);
}
unsafe extern "C" {
    pub fn sourcepp_string_array_new(size: usize) -> sourcepp_string_array_t;
}
unsafe extern "C" {
    pub fn sourcepp_string_array_free(array: *mut sourcepp_string_array_t);
}
pub const vpkpp_attribute_e_VPKPP_ATTRIBUTE_NONE: vpkpp_attribute_e = 0;
pub const vpkpp_attribute_e_VPKPP_ATTRIBUTE_ARCHIVE_INDEX: vpkpp_attribute_e = 1;
pub const vpkpp_attribute_e_VPKPP_ATTRIBUTE_LENGTH: vpkpp_attribute_e = 2;
pub const vpkpp_attribute_e_VPKPP_ATTRIBUTE_CRC32: vpkpp_attribute_e = 4;
pub const vpkpp_attribute_e_VPKPP_ATTRIBUTE_PCK_MD5: vpkpp_attribute_e = 8;
pub const vpkpp_attribute_e_VPKPP_ATTRIBUTE_VPK_PRELOADED_DATA: vpkpp_attribute_e = 16;
pub type vpkpp_attribute_e = ::std::os::raw::c_uint;
pub type vpkpp_entry_handle_t = *mut ::std::os::raw::c_void;
unsafe extern "C" {
    pub fn vpkpp_entry_get_flags(handle: vpkpp_entry_handle_t) -> u32;
}
unsafe extern "C" {
    pub fn vpkpp_entry_get_archive_index(handle: vpkpp_entry_handle_t) -> u32;
}
unsafe extern "C" {
    pub fn vpkpp_entry_get_length(handle: vpkpp_entry_handle_t) -> u64;
}
unsafe extern "C" {
    pub fn vpkpp_entry_get_compressed_length(handle: vpkpp_entry_handle_t) -> u64;
}
unsafe extern "C" {
    pub fn vpkpp_entry_get_offset(handle: vpkpp_entry_handle_t) -> u64;
}
unsafe extern "C" {
    pub fn vpkpp_entry_get_extra_data(handle: vpkpp_entry_handle_t) -> sourcepp_buffer_t;
}
unsafe extern "C" {
    pub fn vpkpp_entry_get_crc32(handle: vpkpp_entry_handle_t) -> u32;
}
unsafe extern "C" {
    pub fn vpkpp_entry_is_unbaked(handle: vpkpp_entry_handle_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vpkpp_entry_free(handle: *mut vpkpp_entry_handle_t);
}
pub const vpkpp_entry_compression_type_e_VPKPP_ENTRY_COMPRESSION_TYPE_NO_OVERRIDE:
    vpkpp_entry_compression_type_e = -1;
pub const vpkpp_entry_compression_type_e_VPKPP_ENTRY_COMPRESSION_TYPE_NO_COMPRESS:
    vpkpp_entry_compression_type_e = 0;
pub const vpkpp_entry_compression_type_e_VPKPP_ENTRY_COMPRESSION_TYPE_DEFLATE:
    vpkpp_entry_compression_type_e = 8;
pub const vpkpp_entry_compression_type_e_VPKPP_ENTRY_COMPRESSION_TYPE_BZIP2:
    vpkpp_entry_compression_type_e = 12;
pub const vpkpp_entry_compression_type_e_VPKPP_ENTRY_COMPRESSION_TYPE_LZMA:
    vpkpp_entry_compression_type_e = 14;
pub const vpkpp_entry_compression_type_e_VPKPP_ENTRY_COMPRESSION_TYPE_ZSTD:
    vpkpp_entry_compression_type_e = 93;
pub const vpkpp_entry_compression_type_e_VPKPP_ENTRY_COMPRESSION_TYPE_XZ:
    vpkpp_entry_compression_type_e = 95;
pub type vpkpp_entry_compression_type_e = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpkpp_bake_options_t {
    pub zip_compressionTypeOverride: i16,
    pub zip_compressionStrength: i16,
    pub gma_writeCRCs: u8,
    pub vpk_generateMD5Entries: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of vpkpp_bake_options_t"][::std::mem::size_of::<vpkpp_bake_options_t>() - 6usize];
    ["Alignment of vpkpp_bake_options_t"][::std::mem::align_of::<vpkpp_bake_options_t>() - 2usize];
    ["Offset of field: vpkpp_bake_options_t::zip_compressionTypeOverride"]
        [::std::mem::offset_of!(vpkpp_bake_options_t, zip_compressionTypeOverride) - 0usize];
    ["Offset of field: vpkpp_bake_options_t::zip_compressionStrength"]
        [::std::mem::offset_of!(vpkpp_bake_options_t, zip_compressionStrength) - 2usize];
    ["Offset of field: vpkpp_bake_options_t::gma_writeCRCs"]
        [::std::mem::offset_of!(vpkpp_bake_options_t, gma_writeCRCs) - 4usize];
    ["Offset of field: vpkpp_bake_options_t::vpk_generateMD5Entries"]
        [::std::mem::offset_of!(vpkpp_bake_options_t, vpk_generateMD5Entries) - 5usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vpkpp_entry_options_t {
    pub zip_compressionType: i16,
    pub zip_compressionStrength: i16,
    pub vpk_preloadBytes: u16,
    pub vpk_saveToDirectory: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of vpkpp_entry_options_t"][::std::mem::size_of::<vpkpp_entry_options_t>() - 8usize];
    ["Alignment of vpkpp_entry_options_t"]
        [::std::mem::align_of::<vpkpp_entry_options_t>() - 2usize];
    ["Offset of field: vpkpp_entry_options_t::zip_compressionType"]
        [::std::mem::offset_of!(vpkpp_entry_options_t, zip_compressionType) - 0usize];
    ["Offset of field: vpkpp_entry_options_t::zip_compressionStrength"]
        [::std::mem::offset_of!(vpkpp_entry_options_t, zip_compressionStrength) - 2usize];
    ["Offset of field: vpkpp_entry_options_t::vpk_preloadBytes"]
        [::std::mem::offset_of!(vpkpp_entry_options_t, vpk_preloadBytes) - 4usize];
    ["Offset of field: vpkpp_entry_options_t::vpk_saveToDirectory"]
        [::std::mem::offset_of!(vpkpp_entry_options_t, vpk_saveToDirectory) - 6usize];
};
pub type vpkpp_pack_file_handle_t = *mut ::std::os::raw::c_void;
pub const vpkpp_pack_file_open_property_e_VPKPP_PACK_FILE_OPEN_PROPERTY_DECRYPTION_KEY:
    vpkpp_pack_file_open_property_e = 0;
pub type vpkpp_pack_file_open_property_e = ::std::os::raw::c_uint;
pub type vpkpp_pack_file_open_property_request_t = ::std::option::Option<
    unsafe extern "C" fn(
        handle: vpkpp_pack_file_handle_t,
        property: vpkpp_pack_file_open_property_e,
    ) -> sourcepp_buffer_t,
>;
pub type vpkpp_entry_callback_t = ::std::option::Option<
    unsafe extern "C" fn(path: *const ::std::os::raw::c_char, entry: vpkpp_entry_handle_t),
>;
pub type vpkpp_entry_predicate_t = ::std::option::Option<
    unsafe extern "C" fn(
        path: *const ::std::os::raw::c_char,
        entry: vpkpp_entry_handle_t,
    ) -> ::std::os::raw::c_int,
>;
pub type vpkpp_entry_creation_t = ::std::option::Option<
    unsafe extern "C" fn(path: *const ::std::os::raw::c_char) -> vpkpp_entry_options_t,
>;
unsafe extern "C" {
    pub fn vpkpp_open(
        path: *const ::std::os::raw::c_char,
        callback: vpkpp_entry_callback_t,
        requestProperty: vpkpp_pack_file_open_property_request_t,
    ) -> vpkpp_pack_file_handle_t;
}
unsafe extern "C" {
    pub fn vpkpp_get_openable_extensions() -> sourcepp_string_array_t;
}
unsafe extern "C" {
    pub fn vpkpp_get_guid(handle: vpkpp_pack_file_handle_t) -> sourcepp_string_t;
}
unsafe extern "C" {
    pub fn vpkpp_has_entry_checksums(handle: vpkpp_pack_file_handle_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vpkpp_verify_entry_checksums(
        handle: vpkpp_pack_file_handle_t,
    ) -> sourcepp_string_array_t;
}
unsafe extern "C" {
    pub fn vpkpp_has_pack_file_checksum(handle: vpkpp_pack_file_handle_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vpkpp_verify_pack_file_checksum(
        handle: vpkpp_pack_file_handle_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vpkpp_has_pack_file_signature(handle: vpkpp_pack_file_handle_t)
        -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vpkpp_verify_pack_file_signature(
        handle: vpkpp_pack_file_handle_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vpkpp_is_case_sensitive(handle: vpkpp_pack_file_handle_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vpkpp_has_entry(
        handle: vpkpp_pack_file_handle_t,
        path: *const ::std::os::raw::c_char,
        includeUnbaked: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vpkpp_find_entry(
        handle: vpkpp_pack_file_handle_t,
        path: *const ::std::os::raw::c_char,
        includeUnbaked: ::std::os::raw::c_int,
    ) -> vpkpp_entry_handle_t;
}
unsafe extern "C" {
    pub fn vpkpp_read_entry(
        handle: vpkpp_pack_file_handle_t,
        path: *const ::std::os::raw::c_char,
    ) -> sourcepp_buffer_t;
}
unsafe extern "C" {
    pub fn vpkpp_read_entry_text(
        handle: vpkpp_pack_file_handle_t,
        path: *const ::std::os::raw::c_char,
    ) -> sourcepp_string_t;
}
unsafe extern "C" {
    pub fn vpkpp_is_read_only(handle: vpkpp_pack_file_handle_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vpkpp_add_entry_from_file(
        handle: vpkpp_pack_file_handle_t,
        entryPath: *const ::std::os::raw::c_char,
        filepath: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn vpkpp_add_entry_from_file_with_options(
        handle: vpkpp_pack_file_handle_t,
        entryPath: *const ::std::os::raw::c_char,
        filepath: *const ::std::os::raw::c_char,
        options: vpkpp_entry_options_t,
    );
}
unsafe extern "C" {
    pub fn vpkpp_add_entry_from_mem(
        handle: vpkpp_pack_file_handle_t,
        path: *const ::std::os::raw::c_char,
        buffer: *const ::std::os::raw::c_uchar,
        bufferLen: usize,
    );
}
unsafe extern "C" {
    pub fn vpkpp_add_entry_from_mem_with_options(
        handle: vpkpp_pack_file_handle_t,
        path: *const ::std::os::raw::c_char,
        buffer: *const ::std::os::raw::c_uchar,
        bufferLen: usize,
        options: vpkpp_entry_options_t,
    );
}
unsafe extern "C" {
    pub fn vpkpp_add_directory(
        handle: vpkpp_pack_file_handle_t,
        entryBaseDir: *const ::std::os::raw::c_char,
        dir: *const ::std::os::raw::c_char,
        creation: vpkpp_entry_creation_t,
    );
}
unsafe extern "C" {
    pub fn vpkpp_add_directory_with_options(
        handle: vpkpp_pack_file_handle_t,
        entryBaseDir: *const ::std::os::raw::c_char,
        dir: *const ::std::os::raw::c_char,
        options: vpkpp_entry_options_t,
    );
}
unsafe extern "C" {
    pub fn vpkpp_rename_entry(
        handle: vpkpp_pack_file_handle_t,
        oldPath: *const ::std::os::raw::c_char,
        newPath: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vpkpp_rename_directory(
        handle: vpkpp_pack_file_handle_t,
        oldDir: *const ::std::os::raw::c_char,
        newDir: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vpkpp_remove_entry(
        handle: vpkpp_pack_file_handle_t,
        path: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vpkpp_remove_directory(
        handle: vpkpp_pack_file_handle_t,
        dirName: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vpkpp_bake(
        handle: vpkpp_pack_file_handle_t,
        outputDir: *const ::std::os::raw::c_char,
        callback: vpkpp_entry_callback_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vpkpp_bake_with_options(
        handle: vpkpp_pack_file_handle_t,
        outputDir: *const ::std::os::raw::c_char,
        options: vpkpp_bake_options_t,
        callback: vpkpp_entry_callback_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vpkpp_extract_entry(
        handle: vpkpp_pack_file_handle_t,
        entryPath: *const ::std::os::raw::c_char,
        filepath: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vpkpp_extract_directory(
        handle: vpkpp_pack_file_handle_t,
        dir: *const ::std::os::raw::c_char,
        outputDir: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vpkpp_extract_all(
        handle: vpkpp_pack_file_handle_t,
        outputDir: *const ::std::os::raw::c_char,
        createUnderPackFileDir: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vpkpp_extract_all_if(
        handle: vpkpp_pack_file_handle_t,
        outputDir: *const ::std::os::raw::c_char,
        predicate: vpkpp_entry_predicate_t,
        stripSharedDirs: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vpkpp_get_entry_count(
        handle: vpkpp_pack_file_handle_t,
        includeUnbaked: ::std::os::raw::c_int,
    ) -> usize;
}
unsafe extern "C" {
    pub fn vpkpp_run_for_all_entries(
        handle: vpkpp_pack_file_handle_t,
        operation: vpkpp_entry_callback_t,
        includeUnbaked: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn vpkpp_get_filepath(handle: vpkpp_pack_file_handle_t) -> sourcepp_string_t;
}
unsafe extern "C" {
    pub fn vpkpp_get_truncated_filepath(handle: vpkpp_pack_file_handle_t) -> sourcepp_string_t;
}
unsafe extern "C" {
    pub fn vpkpp_get_filename(handle: vpkpp_pack_file_handle_t) -> sourcepp_string_t;
}
unsafe extern "C" {
    pub fn vpkpp_get_truncated_filename(handle: vpkpp_pack_file_handle_t) -> sourcepp_string_t;
}
unsafe extern "C" {
    pub fn vpkpp_get_filestem(handle: vpkpp_pack_file_handle_t) -> sourcepp_string_t;
}
unsafe extern "C" {
    pub fn vpkpp_get_truncated_filestem(handle: vpkpp_pack_file_handle_t) -> sourcepp_string_t;
}
unsafe extern "C" {
    pub fn vpkpp_get_supported_entry_attributes(
        handle: vpkpp_pack_file_handle_t,
    ) -> vpkpp_attribute_e;
}
unsafe extern "C" {
    pub fn vpkpp_to_string(handle: vpkpp_pack_file_handle_t) -> sourcepp_string_t;
}
unsafe extern "C" {
    pub fn vpkpp_close(handle: *mut vpkpp_pack_file_handle_t);
}
unsafe extern "C" {
    pub fn vpkpp_escape_entry_path_for_write(
        path: *const ::std::os::raw::c_char,
    ) -> sourcepp_string_t;
}
unsafe extern "C" {
    pub fn vpkpp_fgp_create(path: *const ::std::os::raw::c_char) -> vpkpp_pack_file_handle_t;
}
unsafe extern "C" {
    pub fn vpkpp_fgp_open(
        path: *const ::std::os::raw::c_char,
        callback: vpkpp_entry_callback_t,
    ) -> vpkpp_pack_file_handle_t;
}
unsafe extern "C" {
    pub fn vpkpp_fgp_guid(handle: vpkpp_pack_file_handle_t) -> sourcepp_string_t;
}
unsafe extern "C" {
    pub fn vpkpp_fpx_create(path: *const ::std::os::raw::c_char) -> vpkpp_pack_file_handle_t;
}
unsafe extern "C" {
    pub fn vpkpp_fpx_open(
        path: *const ::std::os::raw::c_char,
        callback: vpkpp_entry_callback_t,
    ) -> vpkpp_pack_file_handle_t;
}
unsafe extern "C" {
    pub fn vpkpp_fpx_guid(handle: vpkpp_pack_file_handle_t) -> sourcepp_string_t;
}
unsafe extern "C" {
    pub fn vpkpp_gcf_open(
        path: *const ::std::os::raw::c_char,
        callback: vpkpp_entry_callback_t,
        requestProperty: vpkpp_pack_file_open_property_request_t,
    ) -> vpkpp_pack_file_handle_t;
}
unsafe extern "C" {
    pub fn vpkpp_gcf_guid(handle: vpkpp_pack_file_handle_t) -> sourcepp_string_t;
}
unsafe extern "C" {
    pub fn vpkpp_gcf_get_version(handle: vpkpp_pack_file_handle_t) -> u32;
}
unsafe extern "C" {
    pub fn vpkpp_gcf_get_appid(handle: vpkpp_pack_file_handle_t) -> u32;
}
unsafe extern "C" {
    pub fn vpkpp_gcf_get_app_version(handle: vpkpp_pack_file_handle_t) -> u32;
}
unsafe extern "C" {
    pub fn vpkpp_gma_open(
        path: *const ::std::os::raw::c_char,
        callback: vpkpp_entry_callback_t,
    ) -> vpkpp_pack_file_handle_t;
}
unsafe extern "C" {
    pub fn vpkpp_gma_guid(handle: vpkpp_pack_file_handle_t) -> sourcepp_string_t;
}
unsafe extern "C" {
    pub fn vpkpp_hog_open(
        path: *const ::std::os::raw::c_char,
        callback: vpkpp_entry_callback_t,
    ) -> vpkpp_pack_file_handle_t;
}
unsafe extern "C" {
    pub fn vpkpp_hog_guid(handle: vpkpp_pack_file_handle_t) -> sourcepp_string_t;
}
unsafe extern "C" {
    pub fn vpkpp_ol_open(
        path: *const ::std::os::raw::c_char,
        callback: vpkpp_entry_callback_t,
    ) -> vpkpp_pack_file_handle_t;
}
unsafe extern "C" {
    pub fn vpkpp_ol_guid(handle: vpkpp_pack_file_handle_t) -> sourcepp_string_t;
}
unsafe extern "C" {
    pub fn vpkpp_ol_get_notes(handle: vpkpp_pack_file_handle_t) -> sourcepp_string_t;
}
unsafe extern "C" {
    pub fn vpkpp_ol_get_entry_notes(
        handle: vpkpp_pack_file_handle_t,
        path: *const ::std::os::raw::c_char,
    ) -> sourcepp_string_t;
}
unsafe extern "C" {
    pub fn vpkpp_007_open(
        path: *const ::std::os::raw::c_char,
        callback: vpkpp_entry_callback_t,
    ) -> vpkpp_pack_file_handle_t;
}
unsafe extern "C" {
    pub fn vpkpp_007_guid(handle: vpkpp_pack_file_handle_t) -> sourcepp_string_t;
}
unsafe extern "C" {
    pub fn vpkpp_ore_create(path: *const ::std::os::raw::c_char) -> vpkpp_pack_file_handle_t;
}
unsafe extern "C" {
    pub fn vpkpp_ore_open(
        path: *const ::std::os::raw::c_char,
        callback: vpkpp_entry_callback_t,
    ) -> vpkpp_pack_file_handle_t;
}
unsafe extern "C" {
    pub fn vpkpp_ore_guid(handle: vpkpp_pack_file_handle_t) -> sourcepp_string_t;
}
pub const vpkpp_pak_type_e_VPKPP_PAK_TYPE_PAK: vpkpp_pak_type_e = 0;
pub const vpkpp_pak_type_e_VPKPP_PAK_TYPE_SIN: vpkpp_pak_type_e = 1;
pub const vpkpp_pak_type_e_VPKPP_PAK_TYPE_HROT: vpkpp_pak_type_e = 2;
pub type vpkpp_pak_type_e = ::std::os::raw::c_uint;
unsafe extern "C" {
    pub fn vpkpp_pak_create(path: *const ::std::os::raw::c_char) -> vpkpp_pack_file_handle_t;
}
unsafe extern "C" {
    pub fn vpkpp_pak_create_with_options(
        path: *const ::std::os::raw::c_char,
        type_: vpkpp_pak_type_e,
    ) -> vpkpp_pack_file_handle_t;
}
unsafe extern "C" {
    pub fn vpkpp_pak_open(
        path: *const ::std::os::raw::c_char,
        callback: vpkpp_entry_callback_t,
    ) -> vpkpp_pack_file_handle_t;
}
unsafe extern "C" {
    pub fn vpkpp_pak_guid(handle: vpkpp_pack_file_handle_t) -> sourcepp_string_t;
}
unsafe extern "C" {
    pub fn vpkpp_pak_get_type(handle: vpkpp_pack_file_handle_t) -> vpkpp_pak_type_e;
}
unsafe extern "C" {
    pub fn vpkpp_pak_set_type(handle: vpkpp_pack_file_handle_t, type_: vpkpp_pak_type_e);
}
unsafe extern "C" {
    pub fn vpkpp_pck_create(path: *const ::std::os::raw::c_char) -> vpkpp_pack_file_handle_t;
}
unsafe extern "C" {
    pub fn vpkpp_pck_create_with_options(
        path: *const ::std::os::raw::c_char,
        version: u32,
        godotMajorVersion: u32,
        godotMinorVersion: u32,
        godotPatchVersion: u32,
    ) -> vpkpp_pack_file_handle_t;
}
unsafe extern "C" {
    pub fn vpkpp_pck_open(
        path: *const ::std::os::raw::c_char,
        callback: vpkpp_entry_callback_t,
    ) -> vpkpp_pack_file_handle_t;
}
unsafe extern "C" {
    pub fn vpkpp_pck_guid(handle: vpkpp_pack_file_handle_t) -> sourcepp_string_t;
}
unsafe extern "C" {
    pub fn vpkpp_vpk_create(path: *const ::std::os::raw::c_char) -> vpkpp_pack_file_handle_t;
}
unsafe extern "C" {
    pub fn vpkpp_vpk_create_with_options(
        path: *const ::std::os::raw::c_char,
        version: u32,
    ) -> vpkpp_pack_file_handle_t;
}
unsafe extern "C" {
    pub fn vpkpp_vpk_open(
        path: *const ::std::os::raw::c_char,
        callback: vpkpp_entry_callback_t,
    ) -> vpkpp_pack_file_handle_t;
}
unsafe extern "C" {
    pub fn vpkpp_vpk_guid(handle: vpkpp_pack_file_handle_t) -> sourcepp_string_t;
}
unsafe extern "C" {
    pub fn vpkpp_vpk_generate_keypair_files(path: *const ::std::os::raw::c_char) -> bool;
}
unsafe extern "C" {
    pub fn vpkpp_vpk_sign_from_file(
        handle: vpkpp_pack_file_handle_t,
        filename: *const ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    pub fn vpkpp_vpk_sign_from_mem(
        handle: vpkpp_pack_file_handle_t,
        privateKeyBuffer: *const ::std::os::raw::c_uchar,
        privateKeyLen: usize,
        publicKeyBuffer: *const ::std::os::raw::c_uchar,
        publicKeyLen: usize,
    ) -> bool;
}
unsafe extern "C" {
    pub fn vpkpp_vpk_get_version(handle: vpkpp_pack_file_handle_t) -> u32;
}
unsafe extern "C" {
    pub fn vpkpp_vpk_set_version(handle: vpkpp_pack_file_handle_t, version: u32);
}
unsafe extern "C" {
    pub fn vpkpp_vpk_get_chunk_size(handle: vpkpp_pack_file_handle_t) -> u32;
}
unsafe extern "C" {
    pub fn vpkpp_vpk_set_chunk_size(handle: vpkpp_pack_file_handle_t, chunkSize: u32);
}
unsafe extern "C" {
    pub fn vpkpp_vpk_vtmb_create(path: *const ::std::os::raw::c_char) -> vpkpp_pack_file_handle_t;
}
unsafe extern "C" {
    pub fn vpkpp_vpk_vtmb_open(
        path: *const ::std::os::raw::c_char,
        callback: vpkpp_entry_callback_t,
    ) -> vpkpp_pack_file_handle_t;
}
unsafe extern "C" {
    pub fn vpkpp_vpk_vtmb_guid(handle: vpkpp_pack_file_handle_t) -> sourcepp_string_t;
}
unsafe extern "C" {
    pub fn vpkpp_wad3_create(path: *const ::std::os::raw::c_char) -> vpkpp_pack_file_handle_t;
}
unsafe extern "C" {
    pub fn vpkpp_wad3_open(
        path: *const ::std::os::raw::c_char,
        callback: vpkpp_entry_callback_t,
    ) -> vpkpp_pack_file_handle_t;
}
unsafe extern "C" {
    pub fn vpkpp_wad3_guid(handle: vpkpp_pack_file_handle_t) -> sourcepp_string_t;
}
unsafe extern "C" {
    pub fn vpkpp_xzp_open(
        path: *const ::std::os::raw::c_char,
        callback: vpkpp_entry_callback_t,
    ) -> vpkpp_pack_file_handle_t;
}
unsafe extern "C" {
    pub fn vpkpp_xzp_guid(handle: vpkpp_pack_file_handle_t) -> sourcepp_string_t;
}
unsafe extern "C" {
    pub fn vpkpp_zip_create(path: *const ::std::os::raw::c_char) -> vpkpp_pack_file_handle_t;
}
unsafe extern "C" {
    pub fn vpkpp_zip_open(
        path: *const ::std::os::raw::c_char,
        callback: vpkpp_entry_callback_t,
    ) -> vpkpp_pack_file_handle_t;
}
unsafe extern "C" {
    pub fn vpkpp_zip_guid(handle: vpkpp_pack_file_handle_t) -> sourcepp_string_t;
}
unsafe extern "C" {
    pub fn vpkpp_zip_get_entry_compression_type(
        handle: vpkpp_pack_file_handle_t,
        path: *const ::std::os::raw::c_char,
    ) -> vpkpp_entry_compression_type_e;
}
unsafe extern "C" {
    pub fn vpkpp_zip_set_entry_compression_type(
        handle: vpkpp_pack_file_handle_t,
        path: *const ::std::os::raw::c_char,
        type_: vpkpp_entry_compression_type_e,
    );
}
unsafe extern "C" {
    pub fn vpkpp_zip_get_entry_compression_strength(
        handle: vpkpp_pack_file_handle_t,
        path: *const ::std::os::raw::c_char,
    ) -> i16;
}
unsafe extern "C" {
    pub fn vpkpp_zip_set_entry_compression_strength(
        handle: vpkpp_pack_file_handle_t,
        path: *const ::std::os::raw::c_char,
        strength: i16,
    );
}
